FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/index.html 
RUN echo "<h1> hi From app1 </h1>" > /usr/share/nginx/html/index.html
 
# docker build -t foraiprompt/app1:v1 .
# docker login 
# docker push foraiprompt/app1:v1

