apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    project: expense
    app: fronted
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      app: fronted
      tier: web
  template:
    metadata:
      labels:
        project: expense
        app: fronted
        tier: web
      spec:
        containers:
        - name: app1
          image: foraiprompt/app1:v1
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    project: expense
    app: fronted
    tier: web
  ports:
  - name: app1-svc-port
    protocol: TCP
    port: 80
    targetPort: 80 
---
