FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/index.html 
RUN echo "<h1> hi From app2 </h1>" > /usr/share/nginx/html/index.html


# docker build -t foraiprompt/app2:v1 .
# docker login -u foraiprompt
# docker push foraiprompt/app2:v1